export const resourceData = [
  {
    id: 1,
    title: 'Guía breve para manejar la ansiedad',
    author: 'Dra. Ana López',
    category: 'Ansiedad',
    type: 'Guía',
    price: 'Gratis',
    description: 'Una guía práctica con ejercicios de respiración y estrategias para afrontar momentos de ansiedad.',
    tags: ['respiración', 'emociones', 'autocuidado'],
  },
  {
    id: 2,
    title: 'Técnicas de regulación emocional',
    author: 'Psic. Camila Rojas',
    category: 'Emociones',
    type: 'Artículo',
    price: 'Gratis',
    description: 'Aprende a identificar y nombrar tus emociones para responder con mayor conciencia.',
    tags: ['emociones', 'mindfulness'],
  },
  {
    id: 3,
    title: 'Rutinas de sueño para estudiantes',
    author: 'Dr. Tomás Rivera',
    category: 'Sueño',
    type: 'Video',
    price: 'Premium',
    description: 'Una rutina sencilla para mejorar la calidad del sueño durante periodos de estudio intensivo.',
    tags: ['sueño', 'estrés', 'estudiantes'],
  },
  {
    id: 4,
    title: 'Herramientas para fortalecer la autoestima',
    author: 'Psic. María Torres',
    category: 'Autoestima',
    type: 'Guía',
    price: 'Gratis',
    description: 'Ejercicios orientados a reconocer fortalezas y construir una imagen más compasiva de uno mismo.',
    tags: ['autoestima', 'confianza', 'autocuidado'],
  },
];
